#!/bin/bash
#SBATCH --mail-type=BEGIN,END,FAIL,TIME_LIMIT_80
#SBATCH --qos=medium
#SBATCH --job-name=X9
#SBATCH --output=%A_X9_%a_.out
#SBATCH --error=%A_X9_%a_.err
#SBATCH --account=copan
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4

module load hpc/2015 anaconda/2.3.0
export I_MPI_PMI_LIBRARY=/p/system/slurm/lib/libpmi.so

source activate py36

echo "_______________________________________________"
echo "SLURM JOB ID: $SLURM_JOBID"
echo "$SLURM_NTASKS tasks"
echo "_______________________________________________"

cd ../experiments
srun -n $SLURM_NTASKS --mpi=pmi2 python X_taucrit.py 1 0
